/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: linus1178 (https://sketchfab.com/linus1178)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmo-0ced6fec204b4083a841113d293f6a07
Title: BMO
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const BMO = (props) => {
  const { nodes, materials } = useGLTF('/models/bmo.glb')
  return (
    <Float floatIntensity={1} >
      <group position={[8, 8, 0]} {...props} dispose={null}>

      <mesh

        
        geometry={nodes.Object_4.geometry}
        material={materials.material}
        position={[0, 0.079, 0.181]}
        rotation={[0, -0.5, 0.01]}
        scale={[0.39, 0.39, 0.5]}
        />

      </group>
    </Float>
  )
}

useGLTF.preload('/models/bmo.glb')


export default BMO

