/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KangaroOz 3D (https://sketchfab.com/KangaroOz-3D)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-2021-37763335f74b497e91906986b170b5d1
Title: MacBook Pro 2021
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { gsap } from 'gsap';

const Macbook = (props) => {
  const { nodes, materials } = useGLTF('/models/macbook.glb');
  const groupRef = useRef();

  useEffect(() => {
    if (groupRef.current) {
      gsap.to(groupRef.current.rotation, {
        y: '+=' + Math.PI * 2, // Rotate 360 degrees around Y-axis
        duration: 60, // Duration in seconds (adjust for desired speed)
        ease: 'none', // Linear easing for constant speed
        repeat: -1, // Repeat indefinitely
      });
    }
  }, []);

  return (
    <group
      ref={groupRef}
      {...props}
      dispose={null}
      scale={13}
      position={[-22, -12, -15]}
      rotation={[0, 2.5, 0]}
    >
      <group position={[0.121, 0.007, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.MacBookPro}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.MacBookPro}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.MacBookPro}
      />
    </group>
  );
};

useGLTF.preload('/models/macbook.glb');

export default Macbook;
